name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'ticketing-ms/auth/**'
jobs:
  build:
    defaults:
        run:
          working-directory: ticketing-ms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t qassimov/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push qassimov/auth
