name: tests

on: pull_request

jobs:
  build:
    defaults:
      run:
        working-directory: ticketing-ms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
      - run: cd payments && echo "STRIPE_KEY=$STRIPE_KEY" >> .env && npm install && npm run test:ci
