name: tests

on:
  pull_request:
    paths:
      - 'ticketing-ms/tickets/**'

jobs:
  build:
    defaults:
      run:
        working-directory: ticketing-ms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
